@startuml
title 基于GitHub的实验管理平台--用例图
actor teachers
actor students
actor users
users <|-- teachers
users <|-- students

package 用户用例集 {
users --up-> (登录)
users --up-> (登入)
users --up-> (管理用户信息)
users --up-> (课程选择)
}
package 业务用例集 {
teachers ---> (评分和评价)
teachers ---> (学生列表)
teachers ---> (课程列表)
teachers ---> (管理课程信息)
students ---> (学生列表)
students ---> (查看成绩)
students ---> (课程列表)
}

@enduml