@startuml
title 基于GitHub的实验管理平台--类图
students "1" -- "n"  grades
tests "1" -- "n"  grades
users <|- students
users <|-- teachers
course "1" -- "n" tests

class users {
    <b>user_id</b> （用户ID）
    name （用户真实姓名）
    github_username （用户GitHub账号）
    update_date （用户GitHub账号修改日期）
    password （用户密码）
    disable （用户是否禁用）
    show_users() (显示所有用户)
    alter_password() (修改密码)
    manage_users() (管理用户信息)
    alter_github() (修改GitHub账号)
}
class teachers{
    <b>teacher_id</b> （老师工号）
    department （老师所属部门）
    add_teacher() (新增老师)
    manage_teacher() (管理老师信息)
}
class students{
    <b>student_id</b> （学号）
    class （班级）
    result_sum（成绩汇总）
    web_sum （网站正确与否汇总）
    add_students() (新增学生)
    manage_students() (管理学生信息)
}
class grades {
    <b>student_id</b> （学号）
    <b>course_id</b> （课程编号）
    <b>test_id</b> （实验编号）
    result （分数）
    memo （评价）
    update_date （评改日期）
    set_result() （设置评分）
    set_memo() （设置评价）
    alter_result() （修改评分）
    alter_memo() （修改评价）
}
class course{
    <b>course_id</b>  （课程编号）
    course_name （课程名称）
    show_course() （查看课程列表）
    add_course() (新增课程)
    manage_course() (管理课程信息)
}

class tests {
    <b>test_id</b> （实验编号）
    <b>course_id</b>  （所属课程编号）
    test_title （实验名称）
    show_tests() （查看实验列表）
    add_tests() (新增实验)
    manage_tests() (管理实验信息)
}

@enduml