@startuml
|读者|
start
while (读者所借图书是否录入完毕?)is(否)
    :读者提供借书卡;
|#AntiqueWhite|图书管理员|
    :将借书卡提供给系统;
|系统|
    :验证读者身份和借书条件;
|#AntiqueWhite|图书管理员|
    :所借图书输入系统;
|系统|
    :记录借书信息;
    :修改图书状态和可借阅数量;
    :累加读者借书数量;
end while (是)
    :打印借书清单，交易成功完成;
stop
@enduml